### ISSUE TITLE
FOIA request for 311 calls about water-in-basement and water-in-street

### ISSUE THREAD

**Issue by dbild** [NORCatUofC/rain#3]
All I could find on the city data portal about 311 requests for water in basement/water in street were FOIA requests for the 311 data. (see row 2 https://data.cityofchicago.org/FOIA/FOIA-Request-Log-311/j2p9-gdf5?q=water%20in%20street%20and%20311 )

So I guess not something that the city puts on the data portal? If we wanted this data, would we need to submit a FOIA request?

**Comment by sbeslow** [comment]
It sure looks like someone else did it.  Kinda surprising that they didn't just add it to the portal since someone requested it.  There is also the option to add a request on the open data portal, but that seems to take a really long time to come into fruition.  So, I guess we'll have to ask ourselves if we want that data and for what.  I'm a little skeptical because I wonder how many people actually report their basement flooding to 311??  Things to think about.

As a side note, I created a slack channel for the group now at: https://chihacknight.slack.com/messages/chicago-rain

**Comment by pjsier** [comment]
@dbild Submitted a FOIA request for this yesterday. And according to the [WBEZ article](http://www.heatofthemoment.org/features/flood/) where they had data from 2009 to 2015 aggregated to the zip code level, the highest zip codes had over 7,000 so it sounds like it could be worthwhile.

It also seems interesting because according to that report you posted in #2 it's one of 3 data sources the city uses to track flooding. Also notable that they mention a "computer sewer model" that could be interesting if we get more information about it. Looking through some articles and RFQs now.

**Comment by pjsier** [comment]
Just got the FOIA information back! They've started sending the data in chunks, and it gives us type (water in street or basement), date, time, and the address block (i.e. 1500 N Main St). Still waiting on a chunk of it, and because of the level of detail we won't post the full data non-aggregated, but it looks good so far
